### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by aviraxp** [EraserKing/CloudMusicGear#11]
- Windows 7
- Windows Desktop Client 2.0.1
- Proxy mode
- Not Overseas or CDN
- Bump of Chicken - WILL
- Almost every blocked song
- Can be reproduced

The blocked songs can not be played or downloaded as the log comes with messages like 'This song http://m1.music.126.net/NpHwpSm9vuZ1hULcf-CQjw==/6039617371504973.mp3 is not available on the server.'

**Comment by EraserKing** [comment]
There's nothing I could do now. The songs are removed from their servers.
