### ISSUE TITLE
Cannot running on WinXP SP3

### ISSUE THREAD

**Issue by kmahyyg** [EraserKing/CloudMusicGear#13]
- Windows XP SP3
- Desktop , The latest verison (0.9) till now
- Cannot Run!
- Yunnan Telecom
- Cannot Run!
- 不是有效的Win32运行程序！
- Cannot Run!

**Comment by EraserKing** [comment]
It's on .NET Framework 4.5, which doesn't support Windows XP now. You could try to recompile it by downgrade the target framework, but I don't know whether this works.

Anyway I suggest not waste time on this project anymore, as it's not supported, and no function is expected to be working now.
