### ISSUE TITLE
Appreciate

### ISSUE THREAD

**Issue by ldk62387237** [EraserKing/CloudMusicGear#15]

**Comment by EraserKing** [comment]
I'm afraid this is impossible. The client is somehow encrypted while I cannot solve this.
If you have a good way please let me know.

**Comment by ldk62387237** [comment]
But I just use your tool and it succeeded

**Comment by ldk62387237** [comment]
Maybe since my client is different？

**Comment by ldk62387237** [comment]
When I use your tool and also set the http on the client, at the first time
there is still a heap of musics are grey,  but then after 30seconds and I
refresh the playlist, it's generally be white

**Comment by ldk62387237** [comment]
If you want me to keep secert to it, I understand, and I promise I will

**Comment by EraserKing** [comment]
Please don't spam.

Can you tell me your client version? Since 2.0.5 (not 100% sure), the response to the client is encrypted so I cannot parse and do any modification to it. I don't track the latest version but I guess it would still be so.
Due to this issue, the tool is no longer working.

**Comment by ldk62387237** [comment]
I test it again and it doesn’t work now… So sorry to disturb your work, and this is the screenshot.
What was happened is the songs did be white, But when you click it, it will skip to the song which don’t have region restrict. And sorry for the spam. 

I know several way to crack the region restrict, but all of them are not perfect and even some API which I found last week was forriden now, I found this API in a script which was written by the JS, here is the link: https://greasyfork.org/zh-CN/scripts/28573-163music  And the api I use before is http://ouo.us/fm/163/?id=   (I put the SONG ID after “=”) 

Expect API，the other ways for what I found is use vpn(it’s usually cost) or proxifier(It works but sometimes chrome will crash because of it, and it’s pretty slow)  

And the reason why I found your github is according to a plug-in of Xp framework, in the “read.md”, He mention you and another one” https://github.com/yanunon/NeteaseCloudMusic”. 

This is what he said: # Unblock163MusicClient - Xposed

Xposed version of EraserKing's [Unblock163MusicClient](https://github.com/EraserKing/Unblock163MusicClient).

Compatible with app v3/v4.


## Thanks

Thanks EraserKing for his Original Windows version [https://github.com/EraserKing/Unblock163MusicClient]

Thanks yanunon for his API analysis! [https://github.com/yanunon/NeteaseCloudMusic]

And finally I hope you can analysis his plugin since even through I can’t play the region-restrict song, But I can still download it, and  even download the music which need be paid. 
Finally I hope I can help you. 

Please look at it@_@, I am a curious 17 boy.
Cheers:
Jeremiah

**Comment by EraserKing** [comment]
I know almost every way you mentioned above. Maybe there's little chance to get it fixed, but I cannot guarantee.
I'll have a look at current version of Windows client when I have some spare time.
