### ISSUE TITLE
启动云音乐UWP时，如果已有下架歌曲存在于播放列表内，则无法直接从播放列表中播放

### ISSUE THREAD

**Issue by starrin** [EraserKing/CloudMusicGear#3]
Operating system: win10
•Client type UWP
•PAC mode / Proxy mode: Proxy mode
•Overseas or not, CDN used or not, which CDN: not Overseas
•Song / Album / Playlist name (how I can locate to that song): Soldier Game
•Whether the issue happens on specific songs, or all songs: any blacklisted songs
•Whether it can be reproduced on web client for the same song: no

PS 从播放列表中移除后重新添加即可正常播放

**Comment by starrin** [comment]
抓包看了下，涉及的API是/eapi/song/enhance/privilege，只要把st字段从-200改成0就行。

**Comment by EraserKing** [comment]
Thanks. Closing,
