### ISSUE TITLE
All locked musics can not be played 

### ISSUE THREAD

**Issue by asdzywx** [EraserKing/CloudMusicGear#6]
- Operating system： Windows 10 x64 home edition
- Client type (Desktop / UWP), version ：Desktop 2.0.1
- PAC mode / Proxy mode：127.0.0.1:3412
- Overseas or not, CDN used or not, which CDN ：In China, no CDN
- Song / Album / Playlist name (how I can locate to that song) ：all locked songs, just like"THE HERO!! ~怒れる拳に火をつけろ~ ——JAM Project (http://music.163.com/#/m/song?id=35806019)"
- Whether the issue happens on specific songs, or all songs ：all locked musics can not be played suddenly in the afternoon on 2016/3/21
- Whether it can be reproduced on web client for the same song：no

I am the new one in Github,よろしくお愿いします。

**Comment by EraserKing** [comment]
This project is not supposed to be working now.
